# Generated by Django 2.2.6 on 2019-10-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='header',
            field=models.ImageField(blank=True, default='headers/default.jpg', null=True, upload_to='headers'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_images',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
