# Generated by Django 2.2.6 on 2019-10-05 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('rate', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('in_stock', models.IntegerField(default=0)),
                ('product_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product_images')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
            ],
        ),
    ]
