# Generated by Django 2.2.6 on 2020-02-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='from_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='to_date',
        ),
    ]
