# Generated by Django 2.2.6 on 2020-02-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200206_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='uuid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
